const services = [
    {id: 1, title: "Professional Website Design", seller: "Ahmed Khan", sellerId: 1, price: "$200", rating: 4.9, reviews: 127, desc: "I will create a modern responsive website for your business. Get a unique, professional, and memorable website design for your brand. Includes 3 concepts, unlimited revisions, and source files.", img: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=600", features: ["3 Initial Concepts", "Source File", "High Resolution", "Commercial Use"], sellerImg: "https://i.pravatar.cc/150?img=1"},
    {id: 2, title: "Professional Logo Design", seller: "Sarah Ali", sellerId: 2, price: "$80", rating: 5.0, reviews: 89, desc: "I will create a modern minimalist logo. Get a unique, professional, and memorable logo design for your brand. Includes 3 concepts, unlimited revisions, and source files.", img: "https://images.unsplash.com/photo-1600132806370-bf17e65e942f?w=600", features: ["3 Initial Concepts", "Source File", "High Resolution", "Commercial Use"], sellerImg: "https://i.pravatar.cc/150?img=2"},
    {id: 3, title: "SEO Blog Writing", seller: "Fatima Noor", sellerId: 3, price: "$30", rating: 4.8, reviews: 156, desc: "Engaging SEO optimized blog posts and articles. 1000+ words with keyword research included.", img: "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600", features: ["1000+ Words", "SEO Optimized", "Keyword Research", "Fast Delivery"], sellerImg: "https://i.pravatar.cc/150?img=3"},
    {id: 4, title: "Social Media Marketing", seller: "Bilal Sheikh", sellerId: 4, price: "$100", rating: 4.7, reviews: 92, desc: "Complete social media management & growth strategy for Instagram, Facebook, and LinkedIn.", img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600", features: ["Content Creation", "Growth Strategy", "Analytics Report", "30 Days Management"], sellerImg: "https://i.pravatar.cc/150?img=4"},
    {id: 5, title: "Video Editing Service", seller: "Usman Raza", sellerId: 5, price: "$80", rating: 4.9, reviews: 203, desc: "Professional video editing for YouTube & commercials. Color grading and motion graphics included.", img: "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600", features: ["Color Grading", "Motion Graphics", "Sound Design", "Fast Turnaround"], sellerImg: "https://i.pravatar.cc/150?img=5"},
    {id: 6, title: "Mobile App Development", seller: "Hassan Javed", sellerId: 6, price: "$500", rating: 5.0, reviews: 67, desc: "Native iOS & Android apps with Flutter/React Native. Complete app with backend integration.", img: "https://images.unsplash.com/photo-1551650975-87deedd944c3?w=600", features: ["iOS & Android", "Backend Integration", "Source Code", "App Store Deploy"], sellerImg: "https://i.pravatar.cc/150?img=6"},
    {id: 7, title: "E-commerce Website", seller: "Zain Malik", sellerId: 7, price: "$400", rating: 4.8, reviews: 134, desc: "Complete Shopify/WooCommerce online stores with payment gateway integration.", img: "https://images.unsplash.com/photo-1547658719-da2b51169166?w=600", features: ["Payment Gateway", "Product Upload", "Responsive Design", "SEO Ready"], sellerImg: "https://i.pravatar.cc/150?img=7"},
    {id: 8, title: "UI/UX Design", seller: "Ayesha Khan", sellerId: 8, price: "$150", rating: 4.9, reviews: 178, desc: "User interface & experience design for web & mobile apps. Figma files included.", img: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600", features: ["Figma Files", "Responsive Design", "Prototyping", "User Research"], sellerImg: "https://i.pravatar.cc/150?img=8"},
    {id: 9, title: "Copywriting Services", seller: "Mariam Shah", sellerId: 9, price: "$40", rating: 4.7, reviews: 98, desc: "Sales copy, email sequences & landing page content that converts.", img: "https://images.unsplash.com/photo-1456324504439-367cee3b3c32?w=600", features: ["Sales Copy", "Email Sequences", "Landing Pages", "Conversion Focused"], sellerImg: "https://i.pravatar.cc/150?img=9"},
    {id: 10, title: "SEO Optimization", seller: "Ali Raza", sellerId: 10, price: "$120", rating: 4.8, reviews: 145, desc: "Complete on-page & off-page SEO for Google ranking. Technical SEO audit included.", img: "https://images.unsplash.com/photo-1432888622747-4eb9a8f2c1bc?w=600", features: ["Technical Audit", "On-Page SEO", "Off-Page SEO", "Monthly Report"], sellerImg: "https://i.pravatar.cc/150?img=10"},
    {id: 11, title: "Motion Graphics", seller: "Saad Ahmed", sellerId: 11, price: "$150", rating: 4.9, reviews: 112, desc: "Animated explainer videos & motion graphics for brands and social media.", img: "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600", features: ["Explainer Videos", "Social Media", "2D Animation", "Voice Over"], sellerImg: "https://i.pravatar.cc/150?img=11"},
    {id: 12, title: "Python Automation", seller: "Kamran Iqbal", sellerId: 12, price: "$90", rating: 5.0, reviews: 76, desc: "Custom Python scripts for automation, data scraping, and task scheduling.", img: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?w=600", features: ["Custom Scripts", "Data Scraping", "API Integration", "Documentation"], sellerImg: "https://i.pravatar.cc/150?img=12"}
];

const sellers = [
    {id: 1, name: "Ahmed Khan", bio: "Full-stack developer with 5+ years experience. Expert in React, Node.js, and WordPress. I have worked with 100+ international clients.", skills: "HTML, CSS, JavaScript, React, Node.js, WordPress, PHP", completedOrders: 234, responseTime: "1 hour", memberSince: "2020", img: "https://i.pravatar.cc/150?img=1"},
    {id: 2, name: "Sarah Ali", bio: "Creative graphic designer specializing in brand identity and logo design. 8+ years of experience working with startups and Fortune 500 companies.", skills: "Logo Design, Brand Identity, Adobe Illustrator, Photoshop, Figma", completedOrders: 456, responseTime: "2 hours", memberSince: "2018", img: "https://i.pravatar.cc/150?img=2"},
    {id: 3, name: "Fatima Noor", bio: "Professional content writer and SEO expert. I help businesses grow their online presence through engaging content and strategic SEO.", skills: "Content Writing, SEO, Blog Writing, Copywriting, Keyword Research", completedOrders: 312, responseTime: "1 hour", memberSince: "2019", img: "https://i.pravatar.cc/150?img=3"},
    {id: 4, name: "Bilal Sheikh", bio: "Digital marketing specialist with expertise in social media growth. Helped 50+ brands increase their online engagement by 300%.", skills: "Social Media Marketing, Facebook Ads, Instagram Growth, Content Strategy", completedOrders: 189, responseTime: "3 hours", memberSince: "2021", img: "https://i.pravatar.cc/150?img=4"},
    {id: 5, name: "Usman Raza", bio: "Video editor and motion graphics artist. Creating compelling visual stories for YouTubers, brands, and agencies for 6+ years.", skills: "Video Editing, After Effects, Premiere Pro, Motion Graphics, Color Grading", completedOrders: 567, responseTime: "2 hours", memberSince: "2019", img: "https://i.pravatar.cc/150?img=5"},
    {id: 6, name: "Hassan Javed", bio: "Mobile app developer specializing in Flutter and React Native. Built 30+ apps with 1M+ downloads combined.", skills: "Flutter, React Native, iOS, Android, Firebase, API Integration", completedOrders: 98, responseTime: "4 hours", memberSince: "2020", img: "https://i.pravatar.cc/150?img=6"},
    {id: 7, name: "Zain Malik", bio: "E-commerce expert and Shopify developer. Helped businesses generate $5M+ in online sales through optimized stores.", skills: "Shopify, WooCommerce, E-commerce, Payment Gateway, Store Design", completedOrders: 267, responseTime: "2 hours", memberSince: "2018", img: "https://i.pravatar.cc/150?img=7"},
    {id: 8, name: "Ayesha Khan", bio: "UI/
        
